### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by adaojunior** [dart-bridge/bridge#3]
I tried to create an bridge application and used the command `new_bridge blog` and it worked fine, then I installed the dependencies and tried to start the application but got this error:

```
←[31mInitialization failed.
FormatException: \ at end of pattern^config\←[39m
```

I'm using Windows 8 and dart 1.11.

I also have a question about which files are public available, for example, what happens if I make a GET request on `http://localhost:8080/packages/app/app.dart` ?

thanks....

**Comment by emilniklas** [comment]
I'm afraid the Windows platform is not supported. That's because of the console environment library is not built with Windows in mind. I will probably return to this issue, but for now, unfortunately Windows is not a priority.

For your second question, the public folder is configurable, but defaults to `web/`

**Comment by adaojunior** [comment]
@emilniklas  Yeah, but since web has a packages folder and your app (lib) will be in that folder it would be public right?

**Comment by emilniklas** [comment]
Yes, that's correct. Just use `pub get` as usual, and the `packages` folder will be symlinked to `web/packages` :)
